name: Node.js CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [15.x]

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v2.4.0
              with:
                  version: 6.20.3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - run: pnpm run deploy
